definitions:
  config:
    /hst:hst/hst:configurations/hippodemospaintegration/hst:abstractpages/base:
      jcr:primaryType: hst:component
      hst:template: base-layout
      hst:componentclassname: com.onehippo.cms7.spa.demo.components.BaseTemplateComponent
      hst:parameternames: [bloomreach, angular, react]
      hst:parametervalues: ['webfile:/freemarker/hippodemospaintegration/base-layout.ftl',
        'webfile:/freemarker/hippodemospaintegration/angular-base-layout.ftl',
        'webfile:/freemarker/hippodemospaintegration/react-base-layout.ftl']
      /menu:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
        hst:parameternames: [selectedMenu, level, menu]
        hst:parametervalues: ['on', '1', main]
        hst:template: base-top-menu
        hst:suppresswastemessage: true
      /top:
        jcr:primaryType: hst:containercomponentreference
        hst:referencecomponent: base/top
      /footer:
        jcr:primaryType: hst:component
        hst:template: base-footer
        hst:suppresswastemessage: true
        /container:
          jcr:primaryType: hst:containercomponentreference
          hst:referencecomponent: base/footer
